name: Mr Raj

on: 
 push:
  branches: [ main ]

jobs: 
  Demo:
    runs-on: Ubuntu-latest
    
    steps:
       - name: Good morning
       - name: Workflow
         run: echo "Good morning, Raj"
      
    
