name: Mr Raj

on: 
  push:
   branches: [ main ]
  schedule: 
   - cron: '0 * * * *'
  
jobs: 
  Demo:
    runs-on: Ubuntu-latest
    
    steps:
       - name: Good morning
         run: echo "Good morning, Raj"
       - name: Workflow
         run: echo "Good morning, Raj"
      
    
